baseurl = "https://gerrywp.github.io/blog"
languageCode = "zh-CN"
title = "云亦海"
publishDir = "docs"
theme = "maupassant"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = false

hasCJKLanguage = true
[author]
  name = "gerry"

[params]
  author = "gerry"
  subtitle = "专注于Go语言(golang)、csharp、移动互联网、项目管理、软件架构"
  keywords = "golang,go语言,go语言笔记,项目管理,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、csharp、项目管理、软件架构等"
  busuanzi = true
  localSearch = true
  
[params.utteranc]
  enable = true
  repo = "gerrywp/blog"    # 存储评论的Repo，格式为 owner/repo
  issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
  theme = "github-light" # 样式主题，有github-light和github-dark两种
	
[menu]
  [[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight=2
  
[markup]
  [markup.highlight]
  style = "vs"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true